#-------------------------------
# General Site Settings
title: Nicolas Constanty
logo: logo.png # You can add own logo.
description: Portfolio of my different projects


#-------------------------------
# Author Settings
author:
  name: Nicolas Constanty
  image: nico.png
  say-hello: Hello, I’m <strong>Nicolas Constanty</strong>
  bio: Game & Software Developer. Passionnate about programming and game creation, I like to join events like Game Jam or Hackathon to learn new things.<p class="hero__subtitle">I also worked on some machine learning projects, like DNAI which is a visual scripting tool focused on AI creation (behaviour, and ml).</p>


#-------------------------------
# Contact links
twitter: https://twitter.com/nicolasconsta15 # Add your Twitter handle
github: https://github.com/Nicolas-Constanty
linkedin: https://www.linkedin.com/in/nicolas-constanty-653232113/
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle

#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
